os: osx

language: crystal
crystal:
  - latest

addons:
  homebrew:
    taps: mongodb/brew
    packages:
    - mongo-c
    - mongodb-community

before_script:
  - brew services start mongodb-community
  - sleep 1
script:
  - crystal spec