version: "3.8"
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  test:
    build: .
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: "27017"
      MONGODB_USER: root
      MONGODB_PASS: example
      MONGODB_DB_NAME: epidote_test
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASS: mysql
      MYSQL_DB_NAME: epidote_test
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - mysql
    command:
      - /bin/sh
      - -c
      - "shards && crystal spec -v -Duse_mongo_static"